name             "vertx"
maintainer       "Ryley Gahagan"
maintainer_email "rgahagan@bloomhealthco.com"
license          "Apache 2.0"
description      "Installs/Configures vertx"
long_description "Installs/Configures vertx"
version          "0.0.1"

depends "ark"
depends "java"
